theme: minima
title: Le blog de Ted.
author: Teddy Le bras
description: Journal de bord d'un développeur
permalink: /:year/:month/:day/:title:output_ext
github_username: TedevFR
linkedin_username: teddylebras
